CREATE TABLE IF NOT EXISTS expantion (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    icon VARCHAR(300) NOT NULL,
);

CREATE TABLE IF NOT EXISTS card (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    mana INT NOT NULL,
    attack INT NOT NULL,
    health INT NOT NULL
    FOREIGN KEY (expantion_id) REFERENCES expantion(id) 
);

CREATE TABLE IF NOT EXISTS user (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    passwordhash VARCHAR(100) NOT NULL,
    passwordsalt VARCHAR(100) NOT NULL
);